name: CI/CD Pipeline for Angular

on:
  push:
    branches:
      - main
      - master # Le pipeline s'exécute lorsque vous poussez sur la branche main
  pull_request:
    branches:
      - main 
      - master # Il s'exécute aussi pour les pull requests vers la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation de l'OS Ubuntu pour exécuter le pipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Vérifie le code depuis le dépôt GitHub

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Utilise la version 16 de Node.js (assurez-vous que c'est compatible avec Angular)

      - name: Install dependencies
        run: npm install  # Installe les dépendances du projet Angular

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless  # Exécute les tests (si vous avez des tests)

      - name: Build Angular app
        run: npm run build --prod --output-path=dist  # Compile l'application en mode production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Utilise un action GitHub pour déployer sur GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Utilise un token GitHub pour l'authentification
          publish_dir: ./dist  # Spécifie le répertoire de sortie où les fichiers construits sont situés
