name: CI/CD Pipeline for Angular App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout du code
    - name: Checkout code
      uses: actions/checkout@v2

    # Installer Node.js et Angular CLI
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Angular CLI
      run: npm install -g @angular/cli@18.2.12

    # Installer les dépendances
    - name: Install dependencies
      run: npm install

    # Build de l'application
    - name: Build Angular app
      run: ng build --configuration production

    # Archive les artefacts pour les étapes suivantes
    - name: Upload dist folder
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Installer les dépendances
    - name: Install dependencies
      run: npm install

    # Exécuter les tests avec ChromeHeadless
    - name: Run tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    # Checkout du code
    - name: Checkout code
      uses: actions/checkout@v2

    # Installer les dépendances et Angular CLI
    - name: Install Angular CLI
      run: npm install -g @angular/cli@18.2.12

    - name: Install dependencies
      run: npm install

    # Déployer sur GitHub Pages
    - name: Deploy to GitHub Pages
      run: |
        mv dist/angularLabs public
        # Déployer sur GitHub Pages
        npm install -g angular-cli-ghpages
        ngh --dir=public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
